# Style

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/RescueStandardError:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/PreferredHashMethods:
  EnforcedStyle: verbose

# Layout

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/IndentationConsistency:
  EnforcedStyle: rails

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/BlockAlignment:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

# RSpec
RSpec/InstanceVariable:
  Enabled: false

RSpec/FilePath:
  Enabled: false

#  Metrics
Metrics/LineLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 250
  Exclude:
    - 'config/routes.rb'

Metrics/MethodLength:
  Max: 20
